/** Petit bac à sable pour essayer l'appli avant de brancher le Sheet. */

export const DEMO = {
  entites: [
    { id: 'e1', type: 'lieu', nom: 'Val-Brumeux', resume: 'Bourg minier au pied des Crocs', tags: 'ville, départ', notes: 'Brouillard permanent depuis l’effondrement de la mine haute.' },
    { id: 'e2', type: 'pnj', nom: 'Maëlle Vertepierre', resume: 'Aubergiste du Sanglier Boiteux', tags: 'alliée', notes: 'Ancienne éclaireuse. Sait où passe la contrebande.',
      niveau: '3', ca: '13', pv_max: '22', force: '11', dexterite: '15', constitution: '12', intelligence: '12', sagesse: '14', charisme: '13' },
    { id: 'e3', type: 'pnj', nom: 'Corvin Sarre', resume: 'Contremaître de la mine', tags: 'suspect', notes: 'Ferme la mine basse « pour raisons de sécurité ». Ment.',
      niveau: '4', ca: '15', pv_max: '31', force: '16', dexterite: '10', constitution: '14', intelligence: '11', sagesse: '9', charisme: '12',
      menace: 'lieutenant', statut: 'actif', plan: 'Vider la mine basse avant que le groupe ne descende. Fait passer les caisses par la galerie nord, de nuit.' },
    { id: 'e4', type: 'faction', nom: 'Compagnie du Creuset', resume: 'Consortium minier de la capitale', tags: 'antagoniste', notes: 'Rachète les concessions après chaque « accident ».' },
    { id: 'e5', type: 'quete', nom: 'Les disparus de la mine basse', resume: 'Quatre mineurs manquent à l’appel', tags: 'principale', notes: 'Récompense annoncée : 200 po. La vraie récompense est ce qu’ils trouveront en bas.' },
    { id: 'e6', type: 'joueur', nom: 'Ilyra', resume: 'Rôdeuse elfe, joueuse : Sarah', tags: 'groupe', notes: '',
      niveau: '4', ca: '15', pv_max: '32', force: '10', dexterite: '18', constitution: '13', intelligence: '11', sagesse: '15', charisme: '12' },
    { id: 'e12', type: 'joueur', nom: 'Bram', resume: 'Guerrier nain, joueur : Tom', tags: 'groupe', notes: '',
      niveau: '4', ca: '18', pv_max: '40', force: '17', dexterite: '10', constitution: '16', intelligence: '9', sagesse: '12', charisme: '10' },
    { id: 'e13', type: 'joueur', nom: 'Sélène', resume: 'Clerc humaine, joueuse : Inès', tags: 'groupe', notes: '',
      niveau: '4', ca: '16', pv_max: '31', force: '12', dexterite: '10', constitution: '14', intelligence: '11', sagesse: '17', charisme: '13' },
    { id: 'e7', type: 'session', nom: 'Session 3', resume: 'Arrivée à Val-Brumeux', tags: '', notes: 'Le groupe a passé la nuit à l’auberge.' },
    { id: 'e8', type: 'monstre', nom: 'Rampant des galeries', resume: 'Chose aveugle qui suit les vibrations', tags: 'mine', notes: 'Attaque toujours la source de bruit la plus proche.',
      niveau: '2', ca: '13', pv_max: '26', force: '15', dexterite: '14', constitution: '15', intelligence: '3', sagesse: '12', charisme: '5',
      taille: 'G', categorie: 'Monstruosité', alignement: 'non aligné', pv_des: '4d10 + 4', vitesse: '9 m, escalade 9 m',
      sens: 'vision aveugle 18 m (aveugle au-delà), Perception passive 12', langues: '—',
      capacites: 'Sens des vibrations. Le rampant repère toute créature en contact avec le sol à 18 m.\nAveugle. Désavantage sur les attaques contre une cible qui ne fait aucun bruit.',
      actions: 'Morsure. Attaque au corps à corps avec une arme : +4 au toucher, allonge 1,50 m, une cible. Touché : 9 (2d6 + 2) dégâts perforants.\nÉtreinte. Attaque au corps à corps : +4 au toucher, une cible de taille M ou inférieure. Touché : la cible est agrippée (DD 12).' },
    { id: 'e9', type: 'pnj', nom: 'Dame Ysolde du Creuset', resume: 'Directrice régionale de la Compagnie', tags: 'antagoniste', notes: 'Ne se salit jamais les mains. Tout passe par Corvin.',
      niveau: '7', ca: '14', pv_max: '58', force: '10', dexterite: '14', constitution: '13', intelligence: '17', sagesse: '15', charisme: '18',
      menace: 'seigneur', statut: 'actif', plan: 'Obtenir la concession de Val-Brumeux entière. Un « accident » de plus devrait suffire à faire signer le conseil.' },
    { id: 'e10', type: 'monstre', nom: 'Garde de la Compagnie', resume: 'Mercenaire en livrée grise', tags: 'compagnie', notes: '',
      niveau: '1/2', ca: '16', pv_max: '16', force: '13', dexterite: '12', constitution: '12', intelligence: '10', sagesse: '11', charisme: '10',
      menace: 'sbire', statut: 'actif', plan: '',
      actions: 'Épée longue. Attaque au corps à corps avec une arme : +3 au toucher, allonge 1,50 m, une cible. Touché : 5 (1d8 + 1) dégâts tranchants.' },
    { id: 'e11', type: 'rencontre', nom: 'Embuscade dans la galerie nord', resume: 'Corvin et ses gardes surprennent le groupe', tags: 'mine', notes: 'Corvin fuit dès qu\'il tombe sous 10 PV : il n\'est pas censé mourir ici.',
      composition: 'e3:1;e10:2;e8:1' },
  ],
  relations: [
    { id: 'r1', source: 'e2', cible: 'e1', type: 'habite à', note: '' },
    { id: 'r2', source: 'e3', cible: 'e1', type: 'habite à', note: '' },
    { id: 'r3', source: 'e3', cible: 'e4', type: 'membre de', note: 'Payé en douce depuis deux ans' },
    { id: 'r4', source: 'e5', cible: 'e1', type: 'situé dans', note: '' },
    { id: 'r5', source: 'e5', cible: 'e2', type: 'quête donnée par', note: '' },
    { id: 'r6', source: 'e6', cible: 'e2', type: 'rencontré par', note: 'Session 3, à l’auberge' },
    { id: 'r7', source: 'e2', cible: 'e7', type: 'apparaît en', note: '' },
    { id: 'r8', source: 'e8', cible: 'e5', type: 'lié à', note: 'C’est lui qui a pris les mineurs' },
    { id: 'r9', source: 'e9', cible: 'e4', type: 'dirige', note: 'Antenne de Val-Brumeux' },
    { id: 'r10', source: 'e3', cible: 'e9', type: 'lieutenant de', note: '' },
    { id: 'r11', source: 'e10', cible: 'e3', type: 'sert', note: '' },
    { id: 'r12', source: 'e11', cible: 'e1', type: 'situé dans', note: 'Galerie nord' },
  ],
};
